### ISSUE TITLE
Flatpak crashes on Ubuntu 21.10

### ISSUE THREAD

**Issue by benduckwdesign** [flathub/com.icons8.Lunacy#6]
com.icons8.Lunacy flatpak crashes shortly after launch with stack trace on Ubuntu 21.10.

Sys info:
```
            .-/+oossssoo+/-.               mikudayo@kitsune 
        `:+ssssssssssssssssss+:`           ---------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 21.10 x86_64 
    .ossssssssssssssssssdMMMNysssso.       Kernel: 5.13.0-37-generic 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Uptime: 2 hours, 41 mins 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Packages: 2612 (dpkg), 71 (flatpak), 11 (snap) 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Shell: bash 5.1.8 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Resolution: 3840x2160, 2560x1440 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   DE: GNOME 40.5 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM Theme: gnome-professional-40.1-dark 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Theme: gnome-professional-40.1-dark [GTK2/3] 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Icons: WhiteSur-dark [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Terminal: gnome-terminal 
  +sssssssssdmydMMMMMMMMddddyssssssss+     CPU: AMD Ryzen 9 3900XT (24) @ 4.000GHz 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      GPU: NVIDIA GeForce RTX 2070 
    .ossssssssssssssssssdMMMNysssso.       GPU: NVIDIA GeForce GT 710 
      -+sssssssssssssssssyyyssss+-         Memory: 7708MiB / 128723MiB 
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.
```

Stack trace:
```
Unhandled exception. System.InvalidOperationException: Default font family name can't be null or empty.
   at Avalonia.Media.FontManager..ctor(IFontManagerImpl platformImpl) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Visuals\Media\FontManager.cs:line 33
   at Avalonia.Media.FontManager.get_Current() in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Visuals\Media\FontManager.cs:line 53
   at Avalonia.Media.TextFormatting.TextCharacters.TryGetRunProperties(ReadOnlySlice`1 text, Typeface typeface, Typeface defaultTypeface, Int32& count) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Visuals\Media\TextFormatting\TextCharacters.cs:line 131
   at Avalonia.Media.TextFormatting.TextCharacters.CreateShapeableRun(ReadOnlySlice`1 text, TextRunProperties defaultProperties) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Visuals\Media\TextFormatting\TextCharacters.cs:line 70
   at Avalonia.Media.TextFormatting.TextCharacters.GetShapeableCharacters() in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Visuals\Media\TextFormatting\TextCharacters.cs:line 48
   at Avalonia.Media.TextFormatting.TextFormatterImpl.FetchTextRuns(ITextSource textSource, Int32 firstTextSourceIndex, TextLineBreak previousLineBreak, TextLineBreak& nextLineBreak) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Visuals\Media\TextFormatting\TextFormatterImpl.cs:line 341
   at Avalonia.Media.TextFormatting.TextFormatterImpl.FormatLine(ITextSource textSource, Int32 firstTextSourceIndex, Double paragraphWidth, TextParagraphProperties paragraphProperties, TextLineBreak previousLineBreak) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Visuals\Media\TextFormatting\TextFormatterImpl.cs:line 15
   at Avalonia.Media.TextFormatting.TextLayout.UpdateLayout() in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Visuals\Media\TextFormatting\TextLayout.cs:line 367
   at Avalonia.Controls.TextBlock.CreateTextLayout(Size constraint, String text) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Controls\TextBlock.cs:line 480
   at Avalonia.Controls.Primitives.AccessText.CreateTextLayout(Size constraint, String text) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Controls\Primitives\AccessText.cs:line 82
   at Avalonia.Controls.TextBlock.get_TextLayout() in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Controls\TextBlock.cs:line 180
   at Avalonia.Controls.TextBlock.MeasureOverride(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Controls\TextBlock.cs:line 549
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 559
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 364
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\LayoutHelper.cs:line 46
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding, Thickness borderThickness) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\LayoutHelper.cs:line 39
   at Avalonia.Controls.Presenters.ContentPresenter.MeasureOverride(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Controls\Presenters\ContentPresenter.cs:line 366
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 559
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 364
   at Avalonia.Controls.Grid.MeasureOverride(Size constraint) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Controls\Grid.cs:line 230
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 559
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 364
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\LayoutHelper.cs:line 46
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding, Thickness borderThickness) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\LayoutHelper.cs:line 39
   at Avalonia.Controls.Border.MeasureOverride(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Controls\Border.cs:line 189
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 559
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 364
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 625
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 559
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 364
   at Avalonia.Controls.StackPanel.MeasureOverride(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Controls\StackPanel.cs:line 207
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 559
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 364
   at Avalonia.Controls.Presenters.ItemVirtualizer.MeasureOverride(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Controls\Presenters\ItemVirtualizer.cs:line 221
   at Avalonia.Controls.Presenters.ItemsPresenter.MeasureOverride(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Controls\Presenters\ItemsPresenter.cs:line 139
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 559
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 364
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\LayoutHelper.cs:line 46
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding, Thickness borderThickness) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\LayoutHelper.cs:line 39
   at Avalonia.Controls.Border.MeasureOverride(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Controls\Border.cs:line 189
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 559
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 364
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 625
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 559
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 364
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\LayoutHelper.cs:line 46
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding, Thickness borderThickness) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\LayoutHelper.cs:line 39
   at Avalonia.Controls.Presenters.ContentPresenter.MeasureOverride(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Controls\Presenters\ContentPresenter.cs:line 366
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 559
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 364
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 625
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 559
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 364
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\LayoutHelper.cs:line 46
   at Lunacy.Controls.Lazy.MeasureOverride(Size availableSize) in /builds/lunacy/lunacy/Lunacy/Lunacy.UI/Controls/Lazy.cs:line 247
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 559
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 364
   at Avalonia.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Controls\Grid.cs:line 1150
   at Avalonia.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Controls\Grid.cs:line 1005
   at Avalonia.Controls.Grid.MeasureOverride(Size constraint) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Controls\Grid.cs:line 436
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 559
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 364
   at Avalonia.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Controls\Grid.cs:line 1150
   at Avalonia.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Controls\Grid.cs:line 1005
   at Avalonia.Controls.Grid.MeasureOverride(Size constraint) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Controls\Grid.cs:line 438
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 559
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 364
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\LayoutHelper.cs:line 46
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding, Thickness borderThickness) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\LayoutHelper.cs:line 39
   at Avalonia.Controls.Presenters.ContentPresenter.MeasureOverride(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Controls\Presenters\ContentPresenter.cs:line 366
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 559
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 364
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\LayoutHelper.cs:line 46
   at Avalonia.Controls.Primitives.VisualLayerManager.MeasureOverride(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Controls\Primitives\VisualLayerManager.cs:line 133
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 559
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 364
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 625
   at Avalonia.Controls.Window.MeasureOverride(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Controls\Window.cs:line 888
   at Avalonia.Controls.WindowBase.MeasureCore(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Controls\WindowBase.cs:line 243
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 364
   at Avalonia.Layout.LayoutManager.Measure(ILayoutable control) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\LayoutManager.cs:line 287
   at Avalonia.Layout.LayoutManager.ExecuteInitialLayoutPass() in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Layout\LayoutManager.cs:line 174
   at Avalonia.Controls.Window.ShowCore(Window parent) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Controls\Window.cs:line 688
   at Avalonia.Controls.Window.Show() in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Controls\Window.cs:line 626
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.ShowMainWindow() in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Controls\ApplicationLifetimes\ClassicDesktopStyleApplicationLifetime.cs:line 141
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Controls\ApplicationLifetimes\ClassicDesktopStyleApplicationLifetime.cs:line 130
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Controls\ApplicationLifetimes\ClassicDesktopStyleApplicationLifetime.cs:line 187
   at Lunacy.Program.Main(String[] args) in /builds/lunacy/lunacy/Lunacy/Lunacy/Program.cs:line 16
```

Issue mentioned here https://github.com/icons8/lunacy-docs/issues/56 . Unsure if issue with flatpak or actual Lunacy deb, but the issue does not occur with snap.

**Comment by garrett** [comment]
This Flatpak is unofficial, as stated on [Flathub.org](https://flathub.org/apps/details/com.icons8.Lunacy): _"This wrapper is not verified by, affiliated with, or supported by Icons8 LLC."_ It was given the OK from the Lunacy developers and is just a repackaging of the Lunacy deb, so it's highly likely the problem exists within the deb version.

(However, the other issue you linked to says it also affects the Snap too.)

It does work here on Fedora, and it does mention a problem with a missing default font. Perhaps it assumes a font exists and it doesnt have some kind of fallback that is on your system? (I don't know what type of font or if this is the case... but it states it at the top of the traceback.)
