### ISSUE TITLE
The app crashes 

### ISSUE THREAD

**Issue by guglovich** [flathub/com.icons8.Lunacy#8]
The app crashes when you press the refresh button in the interface. 

```
OS: Arch Linux 
Kernel: x86_64 Linux 5.17.1-zen1-1-zen
Uptime: 4d 21h 16m
Packages: 1594
Shell: bash
Resolution: 1920x1080
DE: Xfce4
WM: Xfwm4
WM Theme: Default
GTK Theme: Greybird-dark [GTK2]
Icon Theme: elementary-xfce-darker
Font: Sans 10
Disk: 6,4T / 21T (33%)
CPU: AMD A10-7850K Radeon R7, 12 Compute Cores 4C+8G @ 4x 4.1GHz
GPU: AMD Radeon RX 460 Graphics (polaris11, LLVM 13.0.1, DRM 3.44, 5.17.1-zen1-1-zen)
RAM: 8579MiB / 16003MiB
```

Unhandled exception. System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'gnome-terminal' with working directory '/home/perfectionist'. No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(String fileName, String arguments)
   at Lunacy.Services.AppUpdateService.InstallUpdate() in /builds/lunacy/lunacy/Lunacy/Lunacy.UI/Services/AppUpdateService.cs:line 317
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Base\Threading\JobRunner.cs:line 33
   at Avalonia.X11.X11PlatformThreading.HandleX11(CancellationToken cancellationToken) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.X11\X11PlatformThreading.cs:line 169
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.X11\X11PlatformThreading.cs:line 245
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Base\Threading\Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Controls\ApplicationLifetimes\ClassicDesktopStyleApplicationLifetime.cs:line 132
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in C:\Users\brutal\source\repos\gitlab\Avalonia\src\Avalonia.Controls\ApplicationLifetimes\ClassicDesktopStyleApplicationLifetime.cs:line 187
   at Lunacy.Program.Main(String[] args) in /builds/lunacy/lunacy/Lunacy/Lunacy/Program.cs:line 16

**Comment by garrett** [comment]
This is a problem with Lunacy itself, not with the Flatpak. This flatpak is just a repackaging of the official Lunacy deb file.
